service: asu-cic-textract-api

frameworkVersion: '>=1.65.0 <2.0.0'

custom:
  BUCKET_FOR_BILLS: ${self:service}-${self:provider.stage}-bills

provider:
  name: aws
  runtime: nodejs12.x
  timeout: 30
  memorySize: 256
  region: us-east-2
  deploymentBucket:
    maxPreviousDeploymentArtifacts: 10
    blockPublicAccess: true
    serverSideEncryption: AES256

  environment:
    API_KEYS: apikey1, apikey2
    BUCKET_FOR_BILLS: ${self:custom.BUCKET_FOR_BILLS}

  resources:
    Resources:
      GatewayResponseDefault4XX:
        Type: 'AWS::ApiGateway::GatewayResponse'
        Properties:
          ResponseParameters:
            gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
            gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
          ResponseType: DEFAULT_4XX
          RestApiId:
            Ref: 'ApiGatewayRestApi'

      BillsBucket:
        Type: AWS::S3::Bucket
        Properties:
          BucketName: ${self:custom.BUCKET_FOR_BILLS}
          AccessControl: Private
          BucketEncryption:
            ServerSideEncryptionConfiguration:
              - ServerSideEncryptionByDefault:
                  SSEAlgorithm: AES256
          LifecycleConfiguration:
            Rules:
              -
                ExpirationInDays: 14
                Prefix: '/'
                Status: Enabled

  #apiGateway:
    #binaryMediaTypes:
      #- '*/*'

package:
  include:
    - lib/

functions:

  process-bill:
    handler: handler.process
    events:
      - http:
          path: ocr
          method: post
          cors: true
