service: asu-cic-textract-api

frameworkVersion: '>=1.65.0 <2.0.0'

custom:
  BUCKET: ${self:service}-${self:provider.stage}-documents
  BUCKET_REGION: ${self:provider.region}

provider:
  name: aws
  region: us-east-2
  runtime: nodejs12.x
  timeout: 30
  memorySize: 1024

  deploymentBucket:
    maxPreviousDeploymentArtifacts: 10
    blockPublicAccess: true
    serverSideEncryption: AES256

  iamRoleStatements:

    - Effect: "Allow"
      Action:
      - "s3:GetObject"
      - "s3:PutObject"
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - ${self:custom.BUCKET}
            - "/*"

    - Effect: "Allow"
      Action:
        - "textract:StartDocumentAnalysis"
        - "textract:GetDocumentAnalysis"
        - "textract:AnalyzeDocument"
      Resource: "*"

  environment:
    API_KEYS: apikey1,apikey2
    BUCKET: ${self:custom.BUCKET}
    BUCKET_REGION: ${self:custom.BUCKET_REGION}

  apiGateway:
      binaryMediaTypes:
        - '*/*'

resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'

    GatewayResponseDefault5XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_5XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'

    BillsBucket:
      Type: AWS::S3::Bucket
      DeletionPolicy: Retain
      Properties:
        BucketName: ${self:custom.BUCKET}
        AccessControl: Private
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256
        LifecycleConfiguration:
          Rules:
            -
              ExpirationInDays: 14
              Status: Enabled

package:
  exclude:
    - ".*/**"
    - "node_modules/aws-sdk/**" # aws-sdk is available in Lambda NodeJS runtime, don't deploy it
    - "_samples/**"
  include:
    - lib/

functions:

  process-document:
    handler: handler.process
    events:
      - http:
          path: ocr
          method: post
          cors: true
